version: '3.4'

services:
  mysql_db2:
    image: mysql:5.7.22


  phpmyadmin2:
    image: phpmyadmin/phpmyadmin:4.7

  event.api:
    image: ${DOCKER_REGISTRY-}eventapi
    build:
      context: .
      dockerfile: Event.API/Dockerfile
networks:
  events:
    driver: bridge
volumes:
  mysql:
    driver: local
