version: '3.4'

services:
  mysql_db2:
    image: mysql:5.7.22
    container_name: mysql_db2
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: eventdb
      MYSQL_USER: pil_events
      MYSQL_ROOT_PASSWORD: 1a456#idgj_5f@sj*du7fg78@
      SERVICE_NAME: mysql_db2
    networks:
      - events

  phpmyadmin2:
    depends_on:
      - mysql_db2
    container_name: phpmyadmin2
    restart: always
    tty: true
    ports:
      - "4002:80"
    environment:
      PMA_HOST: mysql_db2
      PMA_PORT: pil_events
    networks:
      - events


  event.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mysql_db2
    ports:
      - "8004:80"
